{% set name = "deeprobust" %}
{% set version = "0.2.8" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deeprobust-{{ version }}.tar.gz
  sha256: 4a615d0e27c71d1f226ee28055f166de472b48038fd631378d39ef3d23eceda1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >3.6
  run:
    - gensim >=3.8,<4.0
    - matplotlib-base >=3.1.1
    - networkx >=2.4
    - numba >=0.48.0
    - numpy >=1.17.1
    - pillow >=7.0.0
    - python >3.6
    - scikit-image >=0.0
    - scikit-learn >=0.22.1
    - scipy >=1.3.1
    - tensorboardx >=2.0
    - texttable >=1.6.2
    - pytorch >=1.2.0
    - torchvision >=0.4.0
    - tqdm >=3.0

test:
  imports:
    - deeprobust
    - deeprobust.graph
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/deeprobust/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A PyTorch adversarial learning library, which contains most popular attack and defense algorithms in image domain and graph domain.
  doc_url: https://deeprobust.readthedocs.io/
  dev_url: https://github.com/DSE-MSU/DeepRobust

extra:
  recipe-maintainers:
    - mxr-conda
